
// This file has been generated by the GUI designer. Do not modify.
namespace ComicCompressGTK
{
	public partial class PreferencesDialog
	{
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView treeviewPreferences;
		
		private global::Gtk.VBox vboxContent;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonApply;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ComicCompressGTK.PreferencesDialog
			this.Name = "ComicCompressGTK.PreferencesDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child ComicCompressGTK.PreferencesDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.WidthRequest = 250;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeviewPreferences = new global::Gtk.TreeView ();
			this.treeviewPreferences.CanFocus = true;
			this.treeviewPreferences.Name = "treeviewPreferences";
			this.GtkScrolledWindow.Add (this.treeviewPreferences);
			this.hbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.GtkScrolledWindow]));
			w3.Position = 0;
			w3.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vboxContent = new global::Gtk.VBox ();
			this.vboxContent.Name = "vboxContent";
			this.vboxContent.Spacing = 6;
			this.hbox2.Add (this.vboxContent);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vboxContent]));
			w4.Position = 1;
			w1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox2]));
			w5.Position = 0;
			// Internal child ComicCompressGTK.PreferencesDialog.ActionArea
			global::Gtk.HButtonBox w6 = this.ActionArea;
			w6.Name = "dialog1_ActionArea";
			w6.Spacing = 10;
			w6.BorderWidth = ((uint)(5));
			w6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-ok";
			this.AddActionWidget (this.buttonCancel, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6 [this.buttonCancel]));
			w7.Expand = false;
			w7.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonApply = new global::Gtk.Button ();
			this.buttonApply.CanDefault = true;
			this.buttonApply.CanFocus = true;
			this.buttonApply.Name = "buttonApply";
			this.buttonApply.UseStock = true;
			this.buttonApply.UseUnderline = true;
			this.buttonApply.Label = "gtk-apply";
			this.AddActionWidget (this.buttonApply, -10);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6 [this.buttonApply]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 595;
			this.DefaultHeight = 479;
			this.Show ();
			this.treeviewPreferences.CursorChanged += new global::System.EventHandler (this.OnTreeviewPreferencesCursorChanged);
		}
	}
}
