
// This file has been generated by the GUI designer. Do not modify.
namespace ComicCompressGTK
{
	public partial class DisplayWidget
	{
		private global::Gtk.Table table1;
		
		private global::Gtk.CheckButton checkbuttonPreview;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.CheckButton checkbuttonThumbnail;
		
		private global::Gtk.CheckButton checkbuttonTitle;
		
		private global::Gtk.CheckButton checkbuttonNumber;
		
		private global::Gtk.CheckButton checkbuttonPages;
		
		private global::Gtk.CheckButton checkbuttonPath;
		
		private global::Gtk.Label GtkLabel5;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.SpinButton spinbuttonWidth;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ComicCompressGTK.DisplayWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "ComicCompressGTK.DisplayWidget";
			// Container child ComicCompressGTK.DisplayWidget.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.checkbuttonPreview = new global::Gtk.CheckButton ();
			this.checkbuttonPreview.CanFocus = true;
			this.checkbuttonPreview.Name = "checkbuttonPreview";
			this.checkbuttonPreview.Label = global::Mono.Unix.Catalog.GetString ("Preview current comic");
			this.checkbuttonPreview.Active = true;
			this.checkbuttonPreview.DrawIndicator = true;
			this.checkbuttonPreview.UseUnderline = true;
			this.table1.Add (this.checkbuttonPreview);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkbuttonPreview]));
			w1.TopAttach = ((uint)(2));
			w1.BottomAttach = ((uint)(3));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.checkbuttonThumbnail = new global::Gtk.CheckButton ();
			this.checkbuttonThumbnail.CanFocus = true;
			this.checkbuttonThumbnail.Name = "checkbuttonThumbnail";
			this.checkbuttonThumbnail.Label = global::Mono.Unix.Catalog.GetString ("Thumbnail");
			this.checkbuttonThumbnail.Active = true;
			this.checkbuttonThumbnail.DrawIndicator = true;
			this.checkbuttonThumbnail.UseUnderline = true;
			this.vbox6.Add (this.checkbuttonThumbnail);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.checkbuttonThumbnail]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.checkbuttonTitle = new global::Gtk.CheckButton ();
			this.checkbuttonTitle.CanFocus = true;
			this.checkbuttonTitle.Name = "checkbuttonTitle";
			this.checkbuttonTitle.Label = global::Mono.Unix.Catalog.GetString ("Title");
			this.checkbuttonTitle.Active = true;
			this.checkbuttonTitle.DrawIndicator = true;
			this.checkbuttonTitle.UseUnderline = true;
			this.vbox6.Add (this.checkbuttonTitle);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.checkbuttonTitle]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.checkbuttonNumber = new global::Gtk.CheckButton ();
			this.checkbuttonNumber.CanFocus = true;
			this.checkbuttonNumber.Name = "checkbuttonNumber";
			this.checkbuttonNumber.Label = global::Mono.Unix.Catalog.GetString ("Number");
			this.checkbuttonNumber.Active = true;
			this.checkbuttonNumber.DrawIndicator = true;
			this.checkbuttonNumber.UseUnderline = true;
			this.vbox6.Add (this.checkbuttonNumber);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.checkbuttonNumber]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.checkbuttonPages = new global::Gtk.CheckButton ();
			this.checkbuttonPages.CanFocus = true;
			this.checkbuttonPages.Name = "checkbuttonPages";
			this.checkbuttonPages.Label = global::Mono.Unix.Catalog.GetString ("Pages");
			this.checkbuttonPages.Active = true;
			this.checkbuttonPages.DrawIndicator = true;
			this.checkbuttonPages.UseUnderline = true;
			this.vbox6.Add (this.checkbuttonPages);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.checkbuttonPages]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.checkbuttonPath = new global::Gtk.CheckButton ();
			this.checkbuttonPath.CanFocus = true;
			this.checkbuttonPath.Name = "checkbuttonPath";
			this.checkbuttonPath.Label = global::Mono.Unix.Catalog.GetString ("Path");
			this.checkbuttonPath.Active = true;
			this.checkbuttonPath.DrawIndicator = true;
			this.checkbuttonPath.UseUnderline = true;
			this.vbox6.Add (this.checkbuttonPath);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.checkbuttonPath]));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			this.GtkAlignment.Add (this.vbox6);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel5 = new global::Gtk.Label ();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Comic Display Columns</b>");
			this.GtkLabel5.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel5;
			this.table1.Add (this.frame1);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.frame1]));
			w9.RightAttach = ((uint)(2));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Thumbnail Width");
			this.table1.Add (this.label1);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.spinbuttonWidth = new global::Gtk.SpinButton (0D, 10000D, 1D);
			this.spinbuttonWidth.CanFocus = true;
			this.spinbuttonWidth.Name = "spinbuttonWidth";
			this.spinbuttonWidth.Adjustment.PageIncrement = 10D;
			this.spinbuttonWidth.ClimbRate = 1D;
			this.spinbuttonWidth.Numeric = true;
			this.spinbuttonWidth.Value = 100D;
			this.table1.Add (this.spinbuttonWidth);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.spinbuttonWidth]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
