
// This file has been generated by the GUI designer. Do not modify.
namespace ComicCompressGTK
{
	public partial class MiscWidget
	{
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.Label label2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ComicCompressGTK.MiscWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "ComicCompressGTK.MiscWidget";
			// Container child ComicCompressGTK.MiscWidget.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("No Misc Settings Yet");
			this.vbox7.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.label2]));
			w1.Position = 1;
			w1.Expand = false;
			w1.Fill = false;
			this.Add (this.vbox7);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
