
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action OpenComicDirectoryAction;
	
	private global::Gtk.Action EditAction;
	
	private global::Gtk.Action PreferencesAction;
	
	private global::Gtk.Action HelpAction;
	
	private global::Gtk.Action AboutAction1;
	
	private global::Gtk.Action ViewAction;
	
	private global::Gtk.Action ComicAction;
	
	private global::Gtk.Action AddComicDirectoryAction;
	
	private global::Gtk.Action ClearComicsAction;
	
	private global::Gtk.Action ImportCompressedComicAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.ScrolledWindow scrolledwindow1;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Frame frameCurrentComic;
	
	private global::Gtk.Alignment GtkAlignment1;
	
	private global::ComicCompressGTK.ComicViewWidget comicviewwidget1;
	
	private global::Gtk.Label GtkLabel6;
	
	private global::Gtk.Frame frame3;
	
	private global::Gtk.Alignment GtkAlignment2;
	
	private global::Gtk.Table table2;
	
	private global::Gtk.Button buttonOpenPath;
	
	private global::Gtk.Button buttonSingleApply;
	
	private global::Gtk.Button buttonSingleClear;
	
	private global::Gtk.CheckButton checkbuttonNumberNeighbors;
	
	private global::Gtk.Entry entryTitle;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.SpinButton spinbuttonNumber;
	
	private global::Gtk.Label GtkLabel9;
	
	private global::Gtk.Frame frame1;
	
	private global::Gtk.Alignment GtkAlignment;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.Button buttonAllApply;
	
	private global::Gtk.CheckButton checkbuttonNumbered;
	
	private global::Gtk.Entry entryPostfix;
	
	private global::Gtk.Entry entryPrefix;
	
	private global::Gtk.Entry entrySeriesTitle;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.SpinButton spinbuttonBack;
	
	private global::Gtk.SpinButton spinbuttonFront;
	
	private global::Gtk.Label GtkLabel12;
	
	private global::Gtk.Frame frame4;
	
	private global::Gtk.Alignment GtkAlignment3;
	
	private global::Gtk.Table table3;
	
	private global::Gtk.Button buttonCompress;
	
	private global::Gtk.ComboBox comboboxCompressOption;
	
	private global::Gtk.ProgressBar progressbarCompression;
	
	private global::Gtk.Label GtkLabel14;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TreeView treeviewComics;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.OpenComicDirectoryAction = new global::Gtk.Action ("OpenComicDirectoryAction", global::Mono.Unix.Catalog.GetString ("Open Comic Directory"), null, null);
		this.OpenComicDirectoryAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.OpenComicDirectoryAction, null);
		this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.EditAction, null);
		this.PreferencesAction = new global::Gtk.Action ("PreferencesAction", global::Mono.Unix.Catalog.GetString ("Preferences"), null, null);
		this.PreferencesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Preferences");
		w1.Add (this.PreferencesAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.AboutAction1 = new global::Gtk.Action ("AboutAction1", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction1, null);
		this.ViewAction = new global::Gtk.Action ("ViewAction", global::Mono.Unix.Catalog.GetString ("View"), null, null);
		this.ViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("View");
		w1.Add (this.ViewAction, null);
		this.ComicAction = new global::Gtk.Action ("ComicAction", global::Mono.Unix.Catalog.GetString ("Comic"), null, null);
		this.ComicAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Comic");
		w1.Add (this.ComicAction, null);
		this.AddComicDirectoryAction = new global::Gtk.Action ("AddComicDirectoryAction", global::Mono.Unix.Catalog.GetString ("Add Comic Directory"), null, null);
		this.AddComicDirectoryAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add Comic");
		w1.Add (this.AddComicDirectoryAction, null);
		this.ClearComicsAction = new global::Gtk.Action ("ClearComicsAction", global::Mono.Unix.Catalog.GetString ("Clear Comics"), null, null);
		this.ClearComicsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Clear Comics");
		w1.Add (this.ClearComicsAction, null);
		this.ImportCompressedComicAction = new global::Gtk.Action ("ImportCompressedComicAction", global::Mono.Unix.Catalog.GetString ("Import Compressed Comic"), null, null);
		this.ImportCompressedComicAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Import Compressed Comic");
		w1.Add (this.ImportCompressedComicAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Comic Compress");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString (@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='OpenComicDirectoryAction' action='OpenComicDirectoryAction'/><menuitem name='AddComicDirectoryAction' action='AddComicDirectoryAction'/><menuitem name='ImportCompressedComicAction' action='ImportCompressedComicAction'/><menuitem name='ClearComicsAction' action='ClearComicsAction'/></menu><menu name='EditAction' action='EditAction'><menuitem name='PreferencesAction' action='PreferencesAction'/></menu><menu name='ViewAction' action='ViewAction'><menuitem name='ComicAction' action='ComicAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction1' action='AboutAction1'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow1.WidthRequest = 350;
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		global::Gtk.Viewport w3 = new global::Gtk.Viewport ();
		w3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frameCurrentComic = new global::Gtk.Frame ();
		this.frameCurrentComic.Name = "frameCurrentComic";
		// Container child frameCurrentComic.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.comicviewwidget1 = new global::ComicCompressGTK.ComicViewWidget ();
		this.comicviewwidget1.Events = ((global::Gdk.EventMask)(256));
		this.comicviewwidget1.Name = "comicviewwidget1";
		this.GtkAlignment1.Add (this.comicviewwidget1);
		this.frameCurrentComic.Add (this.GtkAlignment1);
		this.GtkLabel6 = new global::Gtk.Label ();
		this.GtkLabel6.Name = "GtkLabel6";
		this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Current Comic</b>");
		this.GtkLabel6.UseMarkup = true;
		this.frameCurrentComic.LabelWidget = this.GtkLabel6;
		this.vbox2.Add (this.frameCurrentComic);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frameCurrentComic]));
		w6.Position = 0;
		w6.Expand = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame ();
		this.frame3.Name = "frame3";
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.table2 = new global::Gtk.Table (((uint)(6)), ((uint)(2)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.buttonOpenPath = new global::Gtk.Button ();
		this.buttonOpenPath.CanFocus = true;
		this.buttonOpenPath.Name = "buttonOpenPath";
		this.buttonOpenPath.UseUnderline = true;
		this.buttonOpenPath.Label = global::Mono.Unix.Catalog.GetString ("Open Path");
		this.table2.Add (this.buttonOpenPath);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.buttonOpenPath]));
		w7.RightAttach = ((uint)(2));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.buttonSingleApply = new global::Gtk.Button ();
		this.buttonSingleApply.CanFocus = true;
		this.buttonSingleApply.Name = "buttonSingleApply";
		this.buttonSingleApply.UseUnderline = true;
		this.buttonSingleApply.Label = global::Mono.Unix.Catalog.GetString ("Apply");
		this.table2.Add (this.buttonSingleApply);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.buttonSingleApply]));
		w8.TopAttach = ((uint)(5));
		w8.BottomAttach = ((uint)(6));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.buttonSingleClear = new global::Gtk.Button ();
		this.buttonSingleClear.CanFocus = true;
		this.buttonSingleClear.Name = "buttonSingleClear";
		this.buttonSingleClear.UseUnderline = true;
		this.buttonSingleClear.Label = global::Mono.Unix.Catalog.GetString ("Clear");
		this.table2.Add (this.buttonSingleClear);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.buttonSingleClear]));
		w9.TopAttach = ((uint)(4));
		w9.BottomAttach = ((uint)(5));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.checkbuttonNumberNeighbors = new global::Gtk.CheckButton ();
		this.checkbuttonNumberNeighbors.CanFocus = true;
		this.checkbuttonNumberNeighbors.Name = "checkbuttonNumberNeighbors";
		this.checkbuttonNumberNeighbors.Label = global::Mono.Unix.Catalog.GetString ("Number Neighbors");
		this.checkbuttonNumberNeighbors.DrawIndicator = true;
		this.checkbuttonNumberNeighbors.UseUnderline = true;
		this.table2.Add (this.checkbuttonNumberNeighbors);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.checkbuttonNumberNeighbors]));
		w10.TopAttach = ((uint)(3));
		w10.BottomAttach = ((uint)(4));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.entryTitle = new global::Gtk.Entry ();
		this.entryTitle.CanFocus = true;
		this.entryTitle.Name = "entryTitle";
		this.entryTitle.IsEditable = true;
		this.entryTitle.InvisibleChar = '●';
		this.table2.Add (this.entryTitle);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.entryTitle]));
		w11.TopAttach = ((uint)(1));
		w11.BottomAttach = ((uint)(2));
		w11.LeftAttach = ((uint)(1));
		w11.RightAttach = ((uint)(2));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.Xalign = 0F;
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Title: ");
		this.table2.Add (this.label6);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.label6]));
		w12.TopAttach = ((uint)(1));
		w12.BottomAttach = ((uint)(2));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.Xalign = 0F;
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Number: ");
		this.table2.Add (this.label7);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2 [this.label7]));
		w13.TopAttach = ((uint)(2));
		w13.BottomAttach = ((uint)(3));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.spinbuttonNumber = new global::Gtk.SpinButton (0D, 1000000000D, 1D);
		this.spinbuttonNumber.CanFocus = true;
		this.spinbuttonNumber.Name = "spinbuttonNumber";
		this.spinbuttonNumber.Adjustment.PageIncrement = 10D;
		this.spinbuttonNumber.ClimbRate = 1D;
		this.spinbuttonNumber.Digits = ((uint)(2));
		this.spinbuttonNumber.Numeric = true;
		this.table2.Add (this.spinbuttonNumber);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2 [this.spinbuttonNumber]));
		w14.TopAttach = ((uint)(2));
		w14.BottomAttach = ((uint)(3));
		w14.LeftAttach = ((uint)(1));
		w14.RightAttach = ((uint)(2));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment2.Add (this.table2);
		this.frame3.Add (this.GtkAlignment2);
		this.GtkLabel9 = new global::Gtk.Label ();
		this.GtkLabel9.Name = "GtkLabel9";
		this.GtkLabel9.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Single Comic</b>");
		this.GtkLabel9.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel9;
		this.vbox2.Add (this.frame3);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame3]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table (((uint)(7)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.buttonAllApply = new global::Gtk.Button ();
		this.buttonAllApply.CanFocus = true;
		this.buttonAllApply.Name = "buttonAllApply";
		this.buttonAllApply.UseUnderline = true;
		this.buttonAllApply.Label = global::Mono.Unix.Catalog.GetString ("Apply");
		this.table1.Add (this.buttonAllApply);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonAllApply]));
		w18.TopAttach = ((uint)(6));
		w18.BottomAttach = ((uint)(7));
		w18.LeftAttach = ((uint)(1));
		w18.RightAttach = ((uint)(2));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.checkbuttonNumbered = new global::Gtk.CheckButton ();
		this.checkbuttonNumbered.CanFocus = true;
		this.checkbuttonNumbered.Name = "checkbuttonNumbered";
		this.checkbuttonNumbered.Label = "";
		this.checkbuttonNumbered.DrawIndicator = true;
		this.checkbuttonNumbered.UseUnderline = true;
		this.table1.Add (this.checkbuttonNumbered);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkbuttonNumbered]));
		w19.TopAttach = ((uint)(5));
		w19.BottomAttach = ((uint)(6));
		w19.LeftAttach = ((uint)(1));
		w19.RightAttach = ((uint)(2));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.entryPostfix = new global::Gtk.Entry ();
		this.entryPostfix.CanFocus = true;
		this.entryPostfix.Name = "entryPostfix";
		this.entryPostfix.IsEditable = true;
		this.entryPostfix.InvisibleChar = '●';
		this.table1.Add (this.entryPostfix);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryPostfix]));
		w20.TopAttach = ((uint)(4));
		w20.BottomAttach = ((uint)(5));
		w20.LeftAttach = ((uint)(1));
		w20.RightAttach = ((uint)(2));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.entryPrefix = new global::Gtk.Entry ();
		this.entryPrefix.CanFocus = true;
		this.entryPrefix.Name = "entryPrefix";
		this.entryPrefix.IsEditable = true;
		this.entryPrefix.InvisibleChar = '●';
		this.table1.Add (this.entryPrefix);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryPrefix]));
		w21.TopAttach = ((uint)(3));
		w21.BottomAttach = ((uint)(4));
		w21.LeftAttach = ((uint)(1));
		w21.RightAttach = ((uint)(2));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.entrySeriesTitle = new global::Gtk.Entry ();
		this.entrySeriesTitle.CanFocus = true;
		this.entrySeriesTitle.Name = "entrySeriesTitle";
		this.entrySeriesTitle.IsEditable = true;
		this.entrySeriesTitle.InvisibleChar = '●';
		this.table1.Add (this.entrySeriesTitle);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1 [this.entrySeriesTitle]));
		w22.LeftAttach = ((uint)(1));
		w22.RightAttach = ((uint)(2));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.Xalign = 0F;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Prefix: ");
		this.table1.Add (this.label1);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
		w23.TopAttach = ((uint)(3));
		w23.BottomAttach = ((uint)(4));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.Xalign = 0F;
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("PostFix: ");
		this.table1.Add (this.label2);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
		w24.TopAttach = ((uint)(4));
		w24.BottomAttach = ((uint)(5));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.Xalign = 0F;
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Remove from front: ");
		this.table1.Add (this.label3);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
		w25.TopAttach = ((uint)(1));
		w25.BottomAttach = ((uint)(2));
		w25.XOptions = ((global::Gtk.AttachOptions)(4));
		w25.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.Xalign = 0F;
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Remove from back: ");
		this.table1.Add (this.label4);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
		w26.TopAttach = ((uint)(2));
		w26.BottomAttach = ((uint)(3));
		w26.XOptions = ((global::Gtk.AttachOptions)(4));
		w26.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.Xalign = 0F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Numbered:");
		this.table1.Add (this.label5);
		global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1 [this.label5]));
		w27.TopAttach = ((uint)(5));
		w27.BottomAttach = ((uint)(6));
		w27.XOptions = ((global::Gtk.AttachOptions)(4));
		w27.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.Xalign = 0F;
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Series Title:");
		this.table1.Add (this.label8);
		global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1 [this.label8]));
		w28.XOptions = ((global::Gtk.AttachOptions)(4));
		w28.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.spinbuttonBack = new global::Gtk.SpinButton (0D, 100D, 1D);
		this.spinbuttonBack.CanFocus = true;
		this.spinbuttonBack.Name = "spinbuttonBack";
		this.spinbuttonBack.Adjustment.PageIncrement = 10D;
		this.spinbuttonBack.ClimbRate = 1D;
		this.spinbuttonBack.Numeric = true;
		this.table1.Add (this.spinbuttonBack);
		global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table1 [this.spinbuttonBack]));
		w29.TopAttach = ((uint)(2));
		w29.BottomAttach = ((uint)(3));
		w29.LeftAttach = ((uint)(1));
		w29.RightAttach = ((uint)(2));
		w29.XOptions = ((global::Gtk.AttachOptions)(4));
		w29.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.spinbuttonFront = new global::Gtk.SpinButton (0D, 100D, 1D);
		this.spinbuttonFront.CanFocus = true;
		this.spinbuttonFront.Name = "spinbuttonFront";
		this.spinbuttonFront.Adjustment.PageIncrement = 10D;
		this.spinbuttonFront.ClimbRate = 1D;
		this.spinbuttonFront.Numeric = true;
		this.table1.Add (this.spinbuttonFront);
		global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table1 [this.spinbuttonFront]));
		w30.TopAttach = ((uint)(1));
		w30.BottomAttach = ((uint)(2));
		w30.LeftAttach = ((uint)(1));
		w30.RightAttach = ((uint)(2));
		w30.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment.Add (this.table1);
		this.frame1.Add (this.GtkAlignment);
		this.GtkLabel12 = new global::Gtk.Label ();
		this.GtkLabel12.Name = "GtkLabel12";
		this.GtkLabel12.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>All Comics</b>");
		this.GtkLabel12.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel12;
		this.vbox2.Add (this.frame1);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
		w33.Position = 2;
		w33.Expand = false;
		w33.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame ();
		this.frame4.Name = "frame4";
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.table3 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.buttonCompress = new global::Gtk.Button ();
		this.buttonCompress.CanFocus = true;
		this.buttonCompress.Name = "buttonCompress";
		this.buttonCompress.UseUnderline = true;
		this.buttonCompress.Label = global::Mono.Unix.Catalog.GetString ("Compress");
		this.table3.Add (this.buttonCompress);
		global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonCompress]));
		w34.TopAttach = ((uint)(1));
		w34.BottomAttach = ((uint)(2));
		w34.RightAttach = ((uint)(3));
		w34.XOptions = ((global::Gtk.AttachOptions)(4));
		w34.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.comboboxCompressOption = global::Gtk.ComboBox.NewText ();
		this.comboboxCompressOption.AppendText (global::Mono.Unix.Catalog.GetString ("Compress all as separate comics"));
		this.comboboxCompressOption.AppendText (global::Mono.Unix.Catalog.GetString ("Compress all as single comic"));
		this.comboboxCompressOption.AppendText (global::Mono.Unix.Catalog.GetString ("Compress selected comic"));
		this.comboboxCompressOption.Name = "comboboxCompressOption";
		this.comboboxCompressOption.Active = 0;
		this.table3.Add (this.comboboxCompressOption);
		global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table3 [this.comboboxCompressOption]));
		w35.RightAttach = ((uint)(3));
		w35.XOptions = ((global::Gtk.AttachOptions)(4));
		w35.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.progressbarCompression = new global::Gtk.ProgressBar ();
		this.progressbarCompression.Name = "progressbarCompression";
		this.table3.Add (this.progressbarCompression);
		global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table3 [this.progressbarCompression]));
		w36.TopAttach = ((uint)(2));
		w36.BottomAttach = ((uint)(3));
		w36.RightAttach = ((uint)(3));
		w36.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment3.Add (this.table3);
		this.frame4.Add (this.GtkAlignment3);
		this.GtkLabel14 = new global::Gtk.Label ();
		this.GtkLabel14.Name = "GtkLabel14";
		this.GtkLabel14.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Compress</b>");
		this.GtkLabel14.UseMarkup = true;
		this.frame4.LabelWidget = this.GtkLabel14;
		this.vbox2.Add (this.frame4);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame4]));
		w39.Position = 3;
		w39.Expand = false;
		w39.Fill = false;
		w3.Add (this.vbox2);
		this.scrolledwindow1.Add (w3);
		this.hbox1.Add (this.scrolledwindow1);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.scrolledwindow1]));
		w42.Position = 0;
		w42.Expand = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeviewComics = new global::Gtk.TreeView ();
		this.treeviewComics.CanFocus = true;
		this.treeviewComics.Name = "treeviewComics";
		this.GtkScrolledWindow.Add (this.treeviewComics);
		this.hbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.GtkScrolledWindow]));
		w44.Position = 1;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w45.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 758;
		this.DefaultHeight = 889;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.OpenComicDirectoryAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.PreferencesAction.Activated += new global::System.EventHandler (this.OnPreferencesActionActivated);
		this.ComicAction.Activated += new global::System.EventHandler (this.OnComicActionActivated);
		this.AddComicDirectoryAction.Activated += new global::System.EventHandler (this.OnAddComicActionActivated);
		this.ClearComicsAction.Activated += new global::System.EventHandler (this.OnClearComicsActionActivated);
		this.ImportCompressedComicAction.Activated += new global::System.EventHandler (this.OnImportCompressedComicActionActivated);
		this.spinbuttonNumber.ValueChanged += new global::System.EventHandler (this.OnSpinbuttonNumberValueChanged);
		this.entryTitle.Changed += new global::System.EventHandler (this.OnEntryTitleChanged);
		this.checkbuttonNumberNeighbors.Toggled += new global::System.EventHandler (this.OnCheckbuttonNumberNeighborsToggled);
		this.buttonSingleClear.Clicked += new global::System.EventHandler (this.OnButtonSingleClearClicked);
		this.buttonSingleApply.Clicked += new global::System.EventHandler (this.OnButtonSingleApplyClicked);
		this.buttonOpenPath.Clicked += new global::System.EventHandler (this.OnButtonOpenPathClicked);
		this.spinbuttonFront.ValueChanged += new global::System.EventHandler (this.OnSpinbuttonFrontValueChanged);
		this.spinbuttonBack.ValueChanged += new global::System.EventHandler (this.OnSpinbuttonBackValueChanged);
		this.entryPrefix.Changed += new global::System.EventHandler (this.OnEntryPrefixChanged);
		this.checkbuttonNumbered.Toggled += new global::System.EventHandler (this.OnCheckbuttonNumberedToggled);
		this.buttonAllApply.Clicked += new global::System.EventHandler (this.OnButtonApplyClicked);
		this.buttonCompress.Clicked += new global::System.EventHandler (this.OnButtonCompressClicked);
		this.treeviewComics.CursorChanged += new global::System.EventHandler (this.OnTreeviewComicsCursorChanged);
	}
}
